#⚠️only non-root builds. 

[YouTube] # All recommended patchs are applied.
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"

[YT_Music] # All recommended patchs are applied.
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
apkmirror-arch = "arm64-v8a"

[Twitch] # All recommended patchs are applied.
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitch-interactive-inc/twitch/"

[TikTok] # All recommended patchs are applied, if TikTok is banned in France or the USA, patches will be disabled, temporarily or permanently.
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"

[Messenger] # All recommended patchs are applied.
apkmirror-dlurl = "https://www.apkmirror.com/apk/facebook-2/messenger/"
apkmirror-arch = "arm64-v8a"
apkmirror-dpi = "360-480dpi"

[NyxMusicPlayer] # All recommended patchs are applied.
apkmirror-dlurl = "https://www.apkmirror.com/apk/awedea/nyx-music-player/"
apkmirror-arch = "arm64-v8a"

# I would add applications based on the popularity of an application and the number of patches to be applied.
# I'd disable applications that haven't received support for a newer version, and patches that haven't been updated in a while.
